// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PersonGroup
{

public enum Client : byte
{
  NONE = 0,
  Person = 1,
  Group = 2,
};


}
