// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PersonGroup
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Client : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Client GetRootAsClient(ByteBuffer _bb) { return GetRootAsClient(_bb, new Client()); }
  public static Client GetRootAsClient(ByteBuffer _bb, Client obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Client __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte ClientType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public PersonGroup.Person? Client_ { get { int o = __p.__offset(6); return o != 0 ? (PersonGroup.Person?)(new PersonGroup.Person()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public PersonGroup.Group? Group { get { int o = __p.__offset(8); return o != 0 ? (PersonGroup.Group?)(new PersonGroup.Group()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<PersonGroup.Client> CreateClient(FlatBufferBuilder builder,
      sbyte client_type = 0,
      Offset<PersonGroup.Person> clientOffset = default(Offset<PersonGroup.Person>),
      Offset<PersonGroup.Group> groupOffset = default(Offset<PersonGroup.Group>)) {
    builder.StartTable(3);
    Client.AddGroup(builder, groupOffset);
    Client.AddClient(builder, clientOffset);
    Client.AddClientType(builder, client_type);
    return Client.EndClient(builder);
  }

  public static void StartClient(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddClientType(FlatBufferBuilder builder, sbyte clientType) { builder.AddSbyte(0, clientType, 0); }
  public static void AddClient(FlatBufferBuilder builder, Offset<PersonGroup.Person> clientOffset) { builder.AddOffset(1, clientOffset.Value, 0); }
  public static void AddGroup(FlatBufferBuilder builder, Offset<PersonGroup.Group> groupOffset) { builder.AddOffset(2, groupOffset.Value, 0); }
  public static Offset<PersonGroup.Client> EndClient(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PersonGroup.Client>(o);
  }
}


static public class ClientVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ClientType*/, 1 /*sbyte*/, 1, false)
      && verifier.VerifyTable(tablePos, 6 /*Client*/, PersonGroup.PersonVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*Group*/, PersonGroup.GroupVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
