// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PersonGroup
{

public enum Gender : sbyte
{
  Male = 0,
  Female = 1,
};


}
