// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PersonGroup
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Root : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Root GetRootAsRoot(ByteBuffer _bb) { return GetRootAsRoot(_bb, new Root()); }
  public static Root GetRootAsRoot(ByteBuffer _bb, Root obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyRoot(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, RootVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Root __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PersonGroup.Client? Client { get { int o = __p.__offset(4); return o != 0 ? (PersonGroup.Client?)(new PersonGroup.Client()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<PersonGroup.Root> CreateRoot(FlatBufferBuilder builder,
      Offset<PersonGroup.Client> clientOffset = default(Offset<PersonGroup.Client>)) {
    builder.StartTable(1);
    Root.AddClient(builder, clientOffset);
    return Root.EndRoot(builder);
  }

  public static void StartRoot(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddClient(FlatBufferBuilder builder, Offset<PersonGroup.Client> clientOffset) { builder.AddOffset(0, clientOffset.Value, 0); }
  public static Offset<PersonGroup.Root> EndRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PersonGroup.Root>(o);
  }
  public static void FinishRootBuffer(FlatBufferBuilder builder, Offset<PersonGroup.Root> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedRootBuffer(FlatBufferBuilder builder, Offset<PersonGroup.Root> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class RootVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Client*/, PersonGroup.ClientVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
