// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PersonGroup
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Root : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Root GetRootAsRoot(ByteBuffer _bb) { return GetRootAsRoot(_bb, new Root()); }
  public static Root GetRootAsRoot(ByteBuffer _bb, Root obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyRoot(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, RootVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Root __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PersonGroup.Client ClientType { get { int o = __p.__offset(4); return o != 0 ? (PersonGroup.Client)__p.bb.Get(o + __p.bb_pos) : PersonGroup.Client.NONE; } }
  public TTable? Client<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public PersonGroup.Person ClientAsPerson() { return Client<PersonGroup.Person>().Value; }
  public PersonGroup.Group ClientAsGroup() { return Client<PersonGroup.Group>().Value; }

  public static Offset<PersonGroup.Root> CreateRoot(FlatBufferBuilder builder,
      PersonGroup.Client client_type = PersonGroup.Client.NONE,
      int clientOffset = 0) {
    builder.StartTable(2);
    Root.AddClient(builder, clientOffset);
    Root.AddClientType(builder, client_type);
    return Root.EndRoot(builder);
  }

  public static void StartRoot(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddClientType(FlatBufferBuilder builder, PersonGroup.Client clientType) { builder.AddByte(0, (byte)clientType, 0); }
  public static void AddClient(FlatBufferBuilder builder, int clientOffset) { builder.AddOffset(1, clientOffset, 0); }
  public static Offset<PersonGroup.Root> EndRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PersonGroup.Root>(o);
  }
  public static void FinishRootBuffer(FlatBufferBuilder builder, Offset<PersonGroup.Root> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedRootBuffer(FlatBufferBuilder builder, Offset<PersonGroup.Root> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class RootVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ClientType*/, 1 /*PersonGroup.Client*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
